name: towmate
description: "Professional towing and roadside assistance service platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  sizer: ^2.0.15
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9

  # State Management & Core
  shared_preferences: ^2.2.2
  
  # Networking
  dio: ^5.7.0
  connectivity_plus: ^5.0.2
  
  # Location Services
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.3
  flutter_typeahead: ^5.2.0
  location: ^7.0.0
  
  # Data & Charts
  fl_chart: ^0.65.0
  
  # UI Enhancements
  fluttertoast: ^8.2.4

  # Additional packages with proper versions
  web: ^1.1.0
  url_launcher: ^6.3.1
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  speech_to_text: ^7.0.0
  translator: ^1.0.0
  intl: ^0.19.0
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  share_plus: ^10.0.2
  camera: ^0.11.0+2
  google_places_flutter: ^2.0.9
  supabase_flutter: ^2.8.0
  flutter_stripe: ^11.1.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/